### ISSUE TITLE
Any CSS required to make it work?

### ISSUE THREAD

**Issue by gustavopch** [manufont/react-swipeable-bottom-sheet#1]
Hello.

I'm trying to use this component, but simply importing it and surrounding the content in the JSX is not working. Is there any required CSS? Perhaps `position: relative` somewhere or `body { height: 100% }`?

Thanks in advance.

**Comment by manufont** [comment]
Hello,

As far as i know, it doesn't requires additional CSS.
Have you tried to set overflowHeight property ? It's set to 0 by default (which hides the component if open property is set to `false`).

**Comment by gustavopch** [comment]
Yes, I've set it but it doesn't work.

**Comment by gustavopch** [comment]
Ok, I think I got the problem. I was using `overflowHeight={64}`. In this case, the content of the SwipeableBottomSheet component must have a height larger than 64px, otherwise it doesn't work. It seems obvious now :stuck_out_tongue:.

Maybe it could throw an error in this situation.

BTW, awesome component!

**Comment by manufont** [comment]
Great, I'll update the readme example in order to avoid confusion.
