### ISSUE TITLE
Content overflowing through left of screen

### ISSUE THREAD

**Issue by gustavopch** [manufont/react-swipeable-bottom-sheet#2]
The content inside the component is overflowing through the left of the screen when the page is long enough to have a scrollbar.

This is the cause:
```javascript
root:{
	width: '100vw',
	height: height,
	position: 'fixed',
	bottom: 0,
	right: 0,
	...this.props.style
}
```

So `width: '100vw'` ignores the width taken by the scrollbar. Together with `right: 0`, the content can't help but overflow a bit through the left of the screen.

This would fix:
```javascript
root:{
	height: height,
	position: 'fixed',
	bottom: 0,
	right: 0,
	left: 0,
	...this.props.style
}
```

**Comment by manufont** [comment]
Good point, thanks for noticing the issue.
I'll add your fix to next release.
