### ISSUE TITLE
Error on setState() on an unmounted component inside HeightUpdater

### ISSUE THREAD

**Issue by gustavopch** [manufont/react-swipeable-bottom-sheet#5]
Hey. Adding the HeightUpdater in the last release started to cause this error:

![image](https://user-images.githubusercontent.com/10941958/30167315-5ebe5888-93bc-11e7-8276-4d9c39facf61.png)

**Comment by manufont** [comment]
Hi,
My bad, I made [this mistake](https://stackoverflow.com/questions/38564080/remove-event-listener-on-unmount-react). I'll fix it ASAP.
