### ISSUE TITLE
Two scrollbars

### ISSUE THREAD

**Issue by gustavopch** [manufont/react-swipeable-bottom-sheet#6]
### Summary:
When the main page already has a scrollbar, a bottom sheet higher than the screen height gets a second scrollbar.

### Steps to reproduce:

 1. Make a page with enough height to get a scrollbar.
 2. Make a bottom sheet with enough height to get a scrollbar when open.
 3. Open the bottom sheet and watch the page getting two scrollbars.

### Expected behavior:
If the bottom sheet is higher than the screen height and gets a scrollbar, no interaction with the main page is expected and therefore it shouldn't be scrollable. In this situation, something like this should be applied: `body { overflow: hidden; }`.

**Comment by manufont** [comment]
I don't think it's an issue with the plugin itself. The plugin shouldn't interfere with your page layout.
Yon can still use the onChange method, and execute `document.body.style.overflow = "hidden"` when the bottom sheet is open.

If your website is a responsive web application, one great solution would be to make your page layout more flexbox-like : Fix html and body to `height: 100%`, and use `overflow: auto` div for scrollable content. In this case, the plugin works great as it's not part of the overflowing content.
I made an static example [here](https://codepen.io/anon/pen/vJqwJy).

**Comment by gustavopch** [comment]
@manufont You're right. There's also the case when the bottom sheet could be higher than the screen height but not covering the whole screen width; then my conclusion of "no interaction with the main page is expected" would be false. Closing this.
